image: softescu/centos:nodejs
stages:
  - ng-lint
  # - ENV-testing
  - devENV-deploy
  - testENV-deploy
  - prodENV-deploy
  - demoENV-deploy

ng-lint:
  stage: ng-lint
  tags:
    - docker-runner
  except:
    -  /^cherry-pick*/
    - first-setup
    - demo
    - master
    - develop
    - test
  script:
    - npm install
    - ng lint ./

# ENV-testing:
#   stage: ENV-testing
#   tags:
#     - docker-runner
#   except:
#     -  /^cherry-pick*/
#     -  /^revert*/
#     - /^demo*/
#     - test
#     - first-setup
#     - production
#     - demo
#     - master
#     - develop
#     - demo-v2
#     - release
#   variables:
#     NG_PARAM_1: $DEV_NG_PARAM_1
#     NG_PARAM_2: $DEV_NG_PARAM_2
#     NG_PARAM_3: $DEV_NG_PARAM_3
#     BUILD_DIRECTORY: $CI_PROJECT_DIR
#   script:
    # - eval $(ssh-agent -s)
    ### Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    # - ssh-add <(echo "${SSH_PRIVATE_KEY}")
    # - mkdir -p ~/.ssh
    # - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    # - git clone git@gitlab.softescu.com:DevOps/DeployServiceAngular.git
    # - if [ -n "${BUILD_DIRECTORY}" ]; then echo "BUILD_DIRECTORY exists. Continue..."; else exit 1;fi
    # - make commit --directory=$CI_PROJECT_DIR/DeployServiceAngular/commit
    ###
    # Customizations
    ###


devENV-deploy:
  stage: devENV-deploy
  tags:
    - docker-runner
  only:
    - develop
  variables:
    ENV_USER: $DEV_USER
    ENV_URL: $DEV_URL
    NG_PARAM_1: $DEV_NG_PARAM_1
    NG_PARAM_2: $DEV_NG_PARAM_2
    NG_PARAM_3: $DEV_NG_PARAM_3
    BUILD_DIRECTORY: /home/${DEV_USER}/repo
  script:
    - eval $(ssh-agent -s)
    ### Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    - ssh-add <(echo "${SSH_PRIVATE_KEY}")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - git clone git@gitlab.softescu.com:DevOps/DeployServiceAngular.git
    - if [ -n "${DEV_USER}" ]; then echo "DEV_USER exists. Continue..."; else exit 1;fi
    - if [ -n "${DEV_URL}" ]; then echo "DEV_URL exists. Continue..."; else exit 1;fi
    - make develop --directory=$CI_PROJECT_DIR/DeployServiceAngular/develop
    ###
    # Customizations
    ###
  environment:
    name: Development
    url: http://$DEV_URL

testENV-deploy:
  stage: testENV-deploy
  tags:
    - docker-runner
  only:
    - test
  variables:
    ENV_USER: $TEST_USER
    ENV_URL: $TEST_URL
    NG_PARAM_1: $TEST_NG_PARAM_1
    NG_PARAM_2: $TEST_NG_PARAM_2
    NG_PARAM_3: $TEST_NG_PARAM_3
    BUILD_DIRECTORY: /home/${TEST_USER}/repo
  script:
    - eval $(ssh-agent -s)
    ### Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    - ssh-add <(echo "${SSH_PRIVATE_KEY}")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - git clone git@gitlab.softescu.com:DevOps/DeployServiceAngular.git
    - if [ -n "${TEST_USER}" ]; then echo "TEST_USER exists. Continue..."; else exit 1;fi
    - if [ -n "${TEST_URL}" ]; then echo "TEST_URL exists. Continue..."; else exit 1;fi
    - make master --directory=$CI_PROJECT_DIR/DeployServiceAngular/master
    ###
    # Customizations
    ###
  environment:
    name: Staging
    url: http://$TEST_URL

prodENV-deploy:
  stage: prodENV-deploy
  tags:
    - docker-runner
  only:
    - master
  variables:
    ENV_USER: $PROD_USER
    ENV_URL: $PROD_URL
    NG_PARAM_1: $PROD_NG_PARAM_1
    NG_PARAM_2: $PROD_NG_PARAM_2
    NG_PARAM_3: $PROD_NG_PARAM_3
    BUILD_DIRECTORY: /home/${PROD_USER}/repo
  script:
    - eval $(ssh-agent -s)
    ### Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    - ssh-add <(echo "${SSH_PRIVATE_KEY}")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - git clone git@gitlab.softescu.com:DevOps/DeployServiceAngular.git
    - if [ -n "${PROD_USER}" ]; then echo "DEMO_USER exists. Continue..."; else exit 1;fi
    - if [ -n "${PROD_URL}" ]; then echo "DEMO_URL exists. Continue..."; else exit 1;fi
    - make production --directory=$CI_PROJECT_DIR/DeployServiceAngular/production
    ###
    # Customizations
    ###
  environment:
    name: Production
    url: http://$DEMO_URL

demoENV-deploy:
  stage: demoENV-deploy
  tags:
    - docker-runner
  only:
    - demo-v2
  variables:
    ENV_USER: $DEMO_USER
    ENV_URL: $DEMO_URL
    NG_PARAM_1: $DEMO_NG_PARAM_1
    NG_PARAM_2: $DEMO_NG_PARAM_2
    NG_PARAM_3: $DEMO_NG_PARAM_3
    BUILD_DIRECTORY: /home/${DEMO_USER}/repo
  script:
    - eval $(ssh-agent -s)
    ### Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    - ssh-add <(echo "${SSH_PRIVATE_KEY}")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - git clone git@gitlab.softescu.com:DevOps/DeployServiceAngular.git
    - if [ -n "${DEMO_USER}" ]; then echo "DEMO_USER exists. Continue..."; else exit 1;fi
    - if [ -n "${DEMO_URL}" ]; then echo "DEMO_URL exists. Continue..."; else exit 1;fi
    - make production --directory=$CI_PROJECT_DIR/DeployServiceAngular/production
    ###
    # Customizations
    ###
  environment:
    name: Demo
    url: http://$DEMO_URL
